# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: More>>
open_in_new: true
# Logo
logo: /blog/img/avatar.jpg

# Sidebar
sidebar: right
widgets:
#- category
#- tag
#- tagcloud
#- archive
#- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon: /assets/images/global/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

# Show number of visitors to each article.
# You can visit https://leancloud.cn get AppID and AppKey.
leancloud_visitors:
  enable: true
  app_id: HmeL0Aj2Mp5kT83LC723uQtt-gzGzoHsz
  app_key: 0dnLgsnCdC4dFXd4wMci4Nyn
